root = '.'
tmp_dir = 'dist'

[build]
cmd = 'go build -o ./dist/xbvr.exe -tags="json1" main.go'
full_bin = './dist/xbvr'
include_ext = ['go']
exclude_dir = ['node_modules', 'cache', 'dist', 'ui', 'tmp']
